### ISSUE TITLE
applicationUrl should be changed

### ISSUE THREAD

**Issue by bluemmc** [dazinator/AspNetRC1toRC2UpgradeTool#28]
I just tried the tool on a hello world example. It converted well (great) and compiled but when running it stalled instead of serving a web page. The reason was that the applicationUrl was wrong. After changing the Url to "http://localhost:50000/" (50000 is the new default in rc2) it worked.

**Comment by dazinator** [comment]
Thanks for raising this. Was that in `LaunchSettings.json` ?

**Comment by bluemmc** [comment]
yes

**Comment by dazinator** [comment]
Could you do me a favour and attach an example of a working LaunchSettings.json?

**Comment by bluemmc** [comment]
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:50000/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "Hosting:Environment": "Development"
      }
    },
    "web": {
      "commandName": "web",
      "environmentVariables": {
        "Hosting:Environment": "Development"
      }
    }
  }
}

**Comment by dazinator** [comment]
Thanks - have read a little more about this change now, according to the docs site, we should be removing the old "web" profile and adding a new one that looks like this:

![image](https://cloud.githubusercontent.com/assets/3176632/15964307/c2824c7a-2f0f-11e6-994b-136302374ada.png)

As documented here: https://docs.asp.net/en/latest/migration/rc1-to-rc2.html#updating-launch-settings-in-visual-studio

The thing is though this would only seem to set the url for the new profile, and other profiles like "IIS Express" wouldn't be affected. Not sure if thats what we want.,

**Comment by dazinator** [comment]
I have added a migration for laucnhSettings.json to the tool now, so hopefully that should fix this issue.
