### ISSUE TITLE
Please prettyprint project.json

### ISSUE THREAD

**Issue by bluemmc** [dazinator/AspNetRC1toRC2UpgradeTool#30]
After converting a hello world project on Windows the project.json file is ONE long line which is difficult to inspect and maintain. It would be nice if it was formatted with line breaks and indent like the source project.json file was.

**Comment by dazinator** [comment]
yeah I noticed this but haven't addressed it yet! In order to work around this, I have been going back into them after in VS, and using ctrl + k + d.  Not ideal at all!

**Comment by bluemmc** [comment]
What tool are you using to output json? For example, newtonsoft has an option to prettyprint things that you could easily use.

**Comment by dazinator** [comment]
That should be fixed now, I have adjusted the approval tests to catch regressions with formatting in future. The actual change I made was a very simple one liner:

https://github.com/dazinator/AspNetRC1toRC2UpgradeTool/commit/0c92e540f3ef40d96a7a1bef879a7d9011772149#diff-57fd8ecb3265e705bfdbee791a4fcbafR46

**Comment by bluemmc** [comment]
Nice!
